name: Build and Test

on:
  push:
    branches: [ master, migrate-to-vcpkg ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: f26ec398c25c4980f33a50391f00a75f7ad62ef7
        vcpkgDirectory: ${{ github.workspace }}/vcpkg
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" -DEACOPY_BUILD_TESTS:BOOL=ON

    - name: Build
      run: |
        cd build
        msbuild ALL_BUILD.vcxproj /p:Configuration=${{ matrix.configuration }} /p:Platform=x64

    - name: Test
      run: |
        cd build
        ctest -C ${{ matrix.configuration }} --output-on-failure

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EACopy-${{ matrix.configuration }}
        path: |
          build/${{ matrix.configuration }}/EACopy.exe
          build/${{ matrix.configuration }}/EACopyService.exe
