name: CI

# This workflow is triggered only on pull requests to the master branch
# Its main purpose is to verify that builds from other developers work correctly
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Configure CMake
      run: |
        mkdir build_${{ matrix.config }}
        cd build_${{ matrix.config }}
        cmake .. -DEACOPY_BUILD_TESTS:BOOL=ON

    - name: Build
      run: |
        cd build_${{ matrix.config }}
        cmake --build . --config ${{ matrix.config }}

    - name: Run Unit Tests
      run: |
        cd build_${{ matrix.config }}/test
        ctest -C ${{ matrix.config }} -V

    - name: Verify Executable Functionality
      run: |
        # Test if EACopy executable works with --help flag
        cd build_${{ matrix.config }}
        ./${{ matrix.config }}/EACopy.exe --help || (echo "EACopy executable failed to run with --help flag" && exit 1)

        # Test if EACopyService executable works with --help flag (Windows only)
        ./${{ matrix.config }}/EACopyService.exe --help || (echo "EACopyService executable failed to run with --help flag" && exit 1)
